name: Docker

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 4 * * *'

jobs:
  # python-ubuntu:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: openzim/docker-publish-action@v5
  #       with:
  #         image-name: rgaudin/python-ubuntu
  #         on-master: 3.8-18.04
  #         restrict-to: rgaudin/python-ubuntu-docker
  #         credentials:
  #           GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
  #           GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
  #           DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
  #           DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}

  # python-redis:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: openzim/docker-publish-action@v5
  #       with:
  #         image-name: rgaudin/python-redis
  #         on-master: 3.8-6.2.4
  #         restrict-to: rgaudin/python-ubuntu-docker
  #         credentials:
  #           GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
  #           GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
  #           DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
  #           DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}

  kiwix-tools:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: openzim/docker-publish-action@v9
        with:
          image-name: rgaudin/kiwix-tools
          registries: ghcr.io
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          context: kiwix-tools
          on-master: nightly
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          restrict-to: rgaudin/docker-images
      - name: Restart dev-library
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployments dev-library-deployment -n zim

  debian:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: openzim/docker-publish-action@v9
        with:
          image-name: rgaudin/debian
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
          context: debian
          on-master: dev
          restrict-to: rgaudin/docker-images

  base-server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: openzim/docker-publish-action@v9
        with:
          image-name: rgaudin/base-server
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          context: base-server
          on-master: latest
          restrict-to: rgaudin/docker-images
